title: "Organizations"
tagline: "for Craft CMS"
description: "A simple parent + child management plugin for Craft CMS"
logo: "https://cdn.flipboxdigital.com/logo/organizations.svg"
url: "https://flipboxfactory.github.io/organizations"
theme: "https://theme.flipboxfactory.com/1.1.6"
google_analytics_tracking_id: "XX-XXXXXXXX-X"